#指令设置
cmd:
  #变量
  var:
    player: '%player%' #正在执行指令的玩家
    year: '%year%' #当前时间-年
    month: '%month%' #月
    day_for_month: '%day_for_month%' #几号
    day_for_week_en: '%day_for_week_en%' #星期几(英文)
    day_for_week_zh: '%day_for_week_ch%' #星期几(中文)
    hour_twelve: '%hour_for_halfday%' #12小时计时
    hour_twenty_four: '%hour_for_day%' #24小时计时
    minute: '%minute%' #分
    second: '%second%' #秒
  #标识此指令是指向一个指令块的指令
  cmd_stack: '>'
  #一些特殊的指令(delay等)的开头
  spi_cmd:
    delay: 'delay'
    sendmsg: 'sendmsg'

#条件设置
conds:
  #普通的条件(如all)
  normal_conds:
    all_player: 'all'
    fakeman: 'fakeman'
  #带参数的条件(如random)
  args_conds:
    negation_players: 'ngt'
    random_player: 'random'
    area_players: 'area'
    range_players: 'range'
    money_has_players: 'money'
  #带前缀的条件(如'#')
  prefix_conds:
    group_players: '#'
    wrold_players: '%'
    permission_has_players: '*'
    cond_in_file: '$'
