name: TimerExecutor
main: com.qing_guang.TimerExecutor.plugin.main.Main
version: 1.7
depend: [Vault]
commands:
  timer:
permissions:
  timer_execute.use:
    default: op
  timer_execute.reload:
    default: op
  timer_execute.test:
    default: op
  timer_execute.stop:
    default: op
